### ISSUE TITLE
Improve readability using bullet points instead of comma-separated items

### ISSUE THREAD

**Issue by gknobloch** [AdobeDocs/experience-manager-apis#46]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which topic?

https://developer.adobe.com/experience-cloud/experience-manager-apis/

### What's wrong with the content?

Not easy to identify entries in comma-separated lists

### What changes do you propose?

Instead of comma-separated list of items, use bullet points
Also make solution titles bold

**Comment by guillaumecarlino** [comment]
I believe we can close the task as the PR was merged.
